runtime: python38 # or another supported version

instance_class: F1

env_variables:
  INSTANCE_UNIX_SOCKET: 'YOUR CONNECTION NAME' # No need to fill in
  MYSQL_USER: 'root' # please put in your credentials
  MYSQL_PASSWORD: 'YOUR PASSWORD' # please put in your credentials
  MYSQL_DB: 'icourse' # please put in your credentials
  MYSQL_HOST: 'YOUR DATABASE' # please put in your credentials

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles